again ...

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,18 +51,23 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Rename artifact to include version
+        run: |
+          ZIP_FILE=$(find target -name "inmoov2-*.zip" | head -n 1)
+          if [ -z "$ZIP_FILE" ]; then
+            echo "Artifact not found!" && exit 1
+          fi
+          NEW_ZIP_NAME="target/inmoov2-${{ env.artifact-version }}.zip"
+          mv "$ZIP_FILE" "$NEW_ZIP_NAME"
+
       - name: Upload to S3
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: "us-east-1"
         run: |
-          FILE_PATH=$(find target -name "*.zip" | head -n 1)
-          if [ -z "$FILE_PATH" ]; then
-            echo "Artifact not found!" && exit 1
-          fi
           S3_URI="s3://your-bucket-name/maven-repo/path/to/artifact/"
-          aws s3 cp "$FILE_PATH" "$S3_URI"
+          aws s3 cp "target/inmoov2-${{ env.artifact-version }}.zip" "$S3_URI"
 
       - name: Verify artifact upload
         run: |
